### ISSUE TITLE
CI: Cargo build getting stuck

### ISSUE THREAD

**Issue by cobward** [spruceid/kepler#71] opened 2021-12-20 18:17 UTC
PRs to the repo aren't building, cargo build is hanging. There are also clippy warns that don't appear when running it locally, for example:
```
error: field is never read: `task`
   --> src/orbit.rs:150:5
    |
150 |     task: Arc<AbortOnDrop<()>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D dead-code` implied by `-D warnings`
```

**Comment by G-0-0** [comment] 2021-12-20 18:44
So far I've identified the issue to be present in cargo with version 1.57.0, but not 1.56.0.

**Comment by G-0-0** [comment] 2021-12-20 19:37
The issue is present in stable and beta (1.57 and 1.58) but appears to be fixed in nightly. This might be the issue (thanks @sbihel): https://github.com/rust-lang/rust/issues/89195

**Closed** 2022-03-01 14:26 UTC
